#%RAML 1.0 DataType
properties:
  code: 
    type: integer
    displayName: Error Code
    description: defined error codes, slightly based on html standards
    example: 1404
  message: 
    type: string
    displayName: Error Message  
    description: a more user-friendly message
    example: sleep not found