#%RAML 1.0 NamedExample
value:  [
          { "id" : 1, 
            "firstname" : "Scoobert", 
            "lastname" : "Doo", 
            "address": "123 Street Syndey, NSW, AU",
            "lastUpdate": "2017-08-08T10:05:41.090Z",
            "version": 1
          },
          { "id" : 1, 
            "firstname" : "Scoobert", 
            "lastname" : "Doo", 
            "address": "123 Street Syndey, NSW, AU",
            "lastUpdate": "2017-08-08T10:05:41.090Z",
            "version": 1
          }           
        ]