#%RAML 1.0 NamedExample
value:  { "id" : 1, 
          "firstname" : "Bart", 
          "lastname" : "Dooby", 
          "address": "123 1st Street, 1st City, USA", 
          "lastUpdate": "2017-08-08T10:05:41.090Z",
          "version": 2
        }
