#%RAML 1.0 NamedExample
value:  { "code": "002AB",
          "name": "shampoo XYZ",
          "description": "shampoo now on sale",
          "price": 1.23,
          "category": "bath",
          "version" : 4,
          "lastUpdate": "2017-08-08T10:06:41.090Z"
        }